import { createSlice } from '@reduxjs/toolkit'; // Import createSlice from Redux Toolkit

// Initial state for the cars slice of the store
const initialState = {
    cars: [ "Model S", "Model 3", "Model X", "Model Y" ] // Default cars array
}

// Create a slice for the car data, which will manage the state related to cars
const carSlice = createSlice({
    name: "car", // Name of the slice (used in Redux DevTools for easier debugging)
    initialState, // Initial state of the slice, which holds the car data
    reducers: {} // No reducers are defined here, so the state is read-only for now
})

// Select function to access the cars state from the Redux store
export const selectCars = state => state.car.cars // Returns the 'cars' array from the 'car' slice of the state

export default carSlice.reducer // Export the reducer function generated by createSlice to be used in the store
